routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/








Auth::routes();
Route::group(['prefix' => LaravelLocalization::setLocale()], function(){
	Route::get("/",["uses"=>"Site\IndexController@index","as"=>"home"]);
	Route::get("/articles",["uses"=>"Site\ArticleController@index","as"=>"articles"]);
	Route::get("/about",["uses"=>"Site\AboutController@index","as"=>"about"]);
	Route::post("/send",["uses"=>"Site\ContactController@send","as"=>"send_contact"]);


    	//dashboard
	Route::group(['prefix' => "dashboard","namespace"=>"Dashboard","middleware"=>["auth"]],function(){
		Route::get("/",["uses"=>"IndexController@index","as"=>"dashboard"]);
		Route::resource("/contact","Contact\ContactController");
		Route::resource("/slider","Slider\SliderController");
		Route::resource("/process","Proces\ProcesController");
		Route::resource("/specialization","Specialization\SpecializationController");
		Route::resource("/user","User\UserController");

		


		//file manager
		Route::get('glide/{path}', function($path){
			$server = \League\Glide\ServerFactory::create([
				'source' => app('filesystem')->disk('public')->getDriver(),
				'cache' => storage_path('glide'),
			]);
			return $server->getImageResponse($path, Input::query());
        })->where('path', '.+');
        
	});

	

});

app/Models/Specialization.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Specialization extends Model
{
    //

    protected $fillable = ["item_id","lang","active","title","description","image"];

    public function scopeActive($query){
        return $query->where('active',1);
    }
}

app/Http/Controllers/Dashboard/Specialization/SpecializationController.php
<?php

namespace App\Http\Controllers\Dashboard\Specialization;

use App\Http\Controllers\Dashboard\DashboardController as Controller;
use Illuminate\Http\Request;
use App\Repositories\SpecializationRepository;
use App\Http\Requests\SpecializationRequest;

class SpecializationController extends Controller
{
    public function __construct(SpecializationRepository $spec_rep){
        $this->spec_rep = $spec_rep;
        $this->template = "dashboard.page.specialization.";
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        
        if(request()->ajax()){
            $this->data = $this->spec_rep->getAllItems();
            return response()->json($this->data);
        }
        $this->template .= "index";
        return $this->render();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $this->template .= "create";
        return $this->render();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SpecializationRequest $request)
    {
        //
        $this->data["response"] = $this->spec_rep->create($request);
        if($this->data["response"])
            return redirect()->route("specialization.edit",[$this->data["response"]->item_id])->with(["success"=>__("dashboard.dashboard_item_saved")]);
        
        return redirect()->back()->withErrors(["errors"=>"Error"]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $this->data["item"] = $this->spec_rep->find($id);
        $this->template .= "edit";
        return $this->render();
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(SpecializationRequest $request, $id)
    {
        //
        $this->data["response"] = $this->spec_rep->update($request,$id);
        if($this->data["response"])
            return redirect()->back()->with(["success"=>__("dashboard.dashboard_item_updateded")]);
        
        return redirect()->back()->withErrors(["errors"=>"Error"]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        if($this->spec_rep->delete($id))
            return response()->json(["success"=>true]);
        return response()->json(["success"=>false],500);
    }
}

resources/views/dashboard/page/specialization/create.blade.php
@extends("dashboard.layout.app")
@section("content")
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="header-icon"><i class="pe-7s-close"></i></div>
        <div class="header-title">
            <h1>{{__("menu.dashboard_item_create")}}</h1>
            <small>&nbsp;</small>
            <ol class="breadcrumb">
                <li><a href="{{route('dashboard')}}">{{__("menu.dashboard_index")}}</a></li>
                <li class="active">{{__("menu.dashboard_item_create")}}</li>
                <li><a href="{{route('specialization.index')}}">{{__("menu.dashboard_back_to_list")}}</a></li>
            </ol>
        </div>
    </section>
    <!-- Main content -->
    <div class="content">
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <div class="panel panel-bd lobidrag">
                    <div class="panel-heading">
                        <div class="panel-title">
                            <h4>&nbsp;</h4>
                        </div>
                    </div>
                    <div class="panel-body">
                        <form action="{{route('specialization.store')}}" method="POST">
                            @csrf
                            @include("dashboard.page.specialization.block.form")
                        </form>
                        
                    </div>
                    <div class="panel-footer">
                        &nbsp;
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- /.content -->
</div>
@endsection

resources/views/dashboard/page/specialization/edit.blade.php
@extends("dashboard.layout.app")
@section("content")
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="header-icon"><i class="pe-7s-close"></i></div>
        <div class="header-title">
            <h1>{{__("menu.dashboard_item_edit")}}</h1>
            <small>&nbsp;</small>
            <ol class="breadcrumb">
                <li><a href="{{route('dashboard')}}">{{__("menu.dashboard_index")}}</a></li>
                <li class="active">{{__("menu.dashboard_item_create")}}</li>
                <li><a href="{{route('specialization.index')}}">{{__("menu.dashboard_back_to_list")}}</a></li>
            </ol>
        </div>
    </section>
    <!-- Main content -->
    <div class="content">
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <div class="panel panel-bd lobidrag">
                    <div class="panel-heading">
                        <div class="panel-title">
                            <h4>&nbsp;</h4>
                        </div>
                    </div>
                    <div class="panel-body">
                        <form action="{{route('specialization.update',[$item->item_id])}}" method="POST">
                            @method("PUT")
                            @csrf
                            @include("dashboard.page.specialization.block.form")
                        </form>
                        
                    </div>
                    <div class="panel-footer">
                        &nbsp;
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- /.content -->
</div>
@endsection

resources/views/dashboard/page/specialization/index.blade.php
@extends("dashboard.layout.app")
@push("style")
    <link rel="stylesheet" href="{{asset('assets/dashboard/plugins/datatables/dataTables.min.css')}}">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.12/css/select2.min.css">
@endpush

@section("content")
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="header-icon"><i class="pe-7s-close"></i></div>
        <div class="header-title">
            <h1>{{__("menu.dashboard_item_list")}}</h1>
            <small>&nbsp;</small>
            <ol class="breadcrumb">
            <li><a href="{{route('dashboard')}}">{{__("menu.dashboard_index")}}</a></li>
                <li class="active">{{__("menu.dashboard_item_list")}}</li>
                <li><a href="{{route('specialization.create')}}">{{__("menu.dashboard_item_create")}}</a></li>
            </ol>
        </div>
    </section>
    <!-- Main content -->
    <div class="content">
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <div class="panel panel-bd lobidrag">
                    <div class="panel-heading">
                        <div class="panel-title">
                            <h4>&nbsp;</h4>
                        </div>
                    </div>
                    <div class="panel-body">
                       <div class="row">
                           <div class="col-md-12">
                                <div class="table-responsive">
                                    <table id="cities" class="table table-bordered table-striped table-hover" >
                                        <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>{{__("dashboard.dashboard_active_label")}}</th>
                                            <th>{{__("dashboard.dashboard_title_label")}}</th>
                                            <th>{{__("dashboard.dashboard_description_label")}}</th>
                                            <th>{{__("dashboard.dashboard_image_label")}}</th>
                                            <th><i class="fa fa-cogs"></i></th>
                                        </tr>
                                        </thead>
                                        <tbody>

                                        </tbody>
                                    </table>
                                </div>

                           </div>
                       </div>
                    </div>
                    <div class="panel-footer">
                        This is standard panel footer
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- /.content -->
</div>
@endsection


@push('scripts')
    <script src="{{asset('assets/dashboard/plugins/datatables/dataTables.min.js')}}"></script>
             <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.12/js/select2.min.js"></script>

    <script>
        $(function () {
            var table = $("#cities").DataTable({
                dom: "<'row'<'col-sm-4'l><'col-sm-4 text-center'B><'col-sm-4'f>>tp",
                "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
                buttons: [
                    {extend: 'copy', className: 'btn-sm'},
                    {extend: 'csv', title: 'meetings', className: 'btn-sm'},
                    {extend: 'excel', title: 'meetings', className: 'btn-sm'},
                    {extend: 'print', className: 'btn-sm'}
                ],
                "columnDefs" : [
                    { "orderable": false, "targets": [5] },
                    { "orderable": true, "targets": [0,1,2,3,4] }
                ],
                "processing": true,
                "serverSide": true,
                "responsive": false,
                "searching": true,
                "autoFill" : true,
                "dataSrc": "tableData",
                "order": [[ 0, "desc" ]],
                "pageLength": 20,
                "ajax": {
                    "url": "{{route("specialization.index")}}",
                    "type": "GET",
                  
                    "dataSrc": function(json){
                        json.data = json.data.map(function(item,index){
                            item.active = item.active ? '<i class="fa fa-check text-success" aria-hidden="true"></i>' : ''

                            item.cogs = '<button ' +
                                            'class="btn btn-xs btn-info  edit_item"'+
                                            'data-item='+(item.item_id)+ 
                                            '><i class="fa fa-pencil"></i></button> '+
                                            '<button '+ 
                                                    'class="btn btn-xs btn-danger delete_item"'+
                                                    'data-item='+(item.id)+    
                                                    '><i class="fa fa-trash"></i></button>';
                          
                            return item;
                        });
                        return json.data;
                    },

                },

                "columns": [
                    { data: "id" },
                    { data: "active" },
                    { data: "title" },
                    { data: "description" },
                    { data: "image" },
                    { data: "cogs" }
                ]





            }).on("draw",function(){

            $('[name="cities_length"]').select2({
                    minimumResultsForSearch: -1
                }); 

                //redirect to edit page
                $("button.edit_item").on('click',function(e){
                    e.preventDefault();
                    var obj = $(this);
                    var url = "{{route('specialization.edit',[':user_id'])}}";
                    url = url.replace(":user_id",obj.data('item'));

                    window.location.href = url;

                });

                //delete user 

                $("button.delete_item").on('click',function(e){
                    e.preventDefault();
                    var obj = $(this);
                    var url = "{{route('specialization.destroy',[':user_id'])}}";
                    url     = url.replace(":user_id",obj.data('item'));
                    swal({
                            title: "{{__('dashboard.dashboard_modal_title')}}",
                            text: "{{__('dashboard.dashboard_modal_text')}}",
                            type: "warning",
                            showCancelButton: true,
                            confirmButtonClass: "btn-danger",
                            confirmButtonText: "{{__('dashboard.dashboard_modal_yes')}}",
                            cancelButtonText: "{{__('dashboard.dashboard_modal_no')}}",
                            closeOnConfirm: false
                        },
                        function(){
                            $.ajax({
                                headers: {
                                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                                },
                                method:"DELETE",
                                url:url,
                                dataType:"JSON"
                            }).done(function(res){
                                table.ajax.reload();
                                swal(
                                    "{{__('dashboard.dashboard_modal_title')}}",
                                    "{{__('dashboard.dashboard_item_updateded')}}",
                                    "success"
                                );
                            }).fail(function(err){
                                swal(
                                    "{{__('dashboard.dashboard_modal_title')}}",
                                    "Error",
                                    "error"
                                );
                            });
                            
                    });
                })
                
            });
        });
    </script>
@endpush        