routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/








Auth::routes();
Route::group(['prefix' => LaravelLocalization::setLocale()], function(){
	Route::get("/",["uses"=>"Site\IndexController@index","as"=>"home"]);
	Route::get("/articles",["uses"=>"Site\ArticleController@index","as"=>"articles"]);
	Route::get("/about",["uses"=>"Site\AboutController@index","as"=>"about"]);
	Route::post("/send",["uses"=>"Site\ContactController@send","as"=>"send_contact"]);


    	//dashboard
	Route::group(['prefix' => "dashboard","namespace"=>"Dashboard","middleware"=>["auth"]],function(){
		Route::get("/",["uses"=>"IndexController@index","as"=>"dashboard"]);
		Route::resource("/contact","Contact\ContactController");
		Route::resource("/slider","Slider\SliderController");
		Route::resource("/process","Proces\ProcesController");
		Route::resource("/specialization","Specialization\SpecializationController");
		Route::resource("/user","User\UserController");

		


		//file manager
		Route::get('glide/{path}', function($path){
			$server = \League\Glide\ServerFactory::create([
				'source' => app('filesystem')->disk('public')->getDriver(),
				'cache' => storage_path('glide'),
			]);
			return $server->getImageResponse($path, Input::query());
        })->where('path', '.+');
        
	});

	

});

app/Http/Controllers/Dashboard/Contact/ContactController.php
<?php

namespace App\Http\Controllers\Dashboard\Contact;


use Illuminate\Http\Request;

use App\Http\Controllers\Dashboard\DashboardController as Controller;

use App\Repositories\ContactRepository;

class ContactController extends Controller
{
    public function __construct(ContactRepository $c_rep){
        $this->c_rep = $c_rep;
        $this->template = "dashboard.page.contact.";
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $this->data["contact"] = $this->c_rep->find($id);
        // dd($this->data);
        $this->template .= "edit";
        
        return $this->render();
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $result  = $this->c_rep->update($request,$id);



        if($result){
            return redirect()->back()->with(["success"=>__("dashboard.dashboard_item_updateded")]);
        }
        return redirect()->back()->withErrors(["errors"=>"Error"]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    //
    protected $data = [];

    protected $template=null;

    protected function render(){
        return view($this->template,$this->data);
    }
}

app/Http/Controllers/Dashboard/IndexController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;

class IndexController extends DashboardController
{
    //
    public function __construct(){
        $this->template = "dashboard.page.";
        
    }

    public function index(){

        $this->template .= "index";
        return $this->render();
    }
}

app/Http/Controllers/Dashboard/Proces/ProcesController.php
<?php

namespace App\Http\Controllers\Dashboard\Proces;

use App\Http\Controllers\Dashboard\DashboardController as Controller;
use Illuminate\Http\Request;
use App\Repositories\ProcessRepository;
use App\Http\Requests\ProcesRequest;

class ProcesController extends Controller
{
    public function __construct(ProcessRepository $proces_rep){
        $this->proces_rep = $proces_rep;
        $this->template = "dashboard.page.process.";
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //

        if(request()->ajax()){
            $this->data = $this->proces_rep->getAllItems();
            return response()->json($this->data);
        }
        $this->template .= "index";
        return $this->render();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $this->template .= "create";
        return $this->render();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProcesRequest $request)
    {
        //
        $this->data["response"] = $this->proces_rep->create($request);
        if($this->data["response"])
            return redirect()->route("process.edit",[$this->data["response"]->item_id])->with(["success"=>__("dashboard.dashboard_item_saved")]);
        
        return redirect()->back()->withErrors(["errors"=>"Error"]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $this->data["item"] = $this->proces_rep->find($id);
        $this->template .= "edit";
        return $this->render();
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProcesRequest $request, $id)
    {
        //
        $this->data["response"] = $this->proces_rep->update($request,$id);
        if($this->data["response"])
            return redirect()->back()->with(["success"=>__("dashboard.dashboard_item_updateded")]);
        
        return redirect()->back()->withErrors(["errors"=>"Error"]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        if($this->proces_rep->delete($id))
            return response()->json(["success"=>true]);
        return response()->json(["success"=>false],500);
    }
}

app/Http/Controllers/Dashboard/Slider/SliderController.php
<?php

namespace App\Http\Controllers\Dashboard\Slider;

use App\Http\Controllers\Dashboard\DashboardController as Controller;
use Illuminate\Http\Request;
use App\Repositories\SliderRepository;
use App\Http\Requests\SliderRequest;

class SliderController extends Controller
{
    public function __construct(SliderRepository $slider_rep){
        $this->slider_rep = $slider_rep;
        $this->template = "dashboard.page.slider.";
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //

        if(request()->ajax()){
            $this->data = $this->slider_rep->getAllItems();
            return response()->json($this->data);
        }
        $this->template .= "index";
        return $this->render();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $this->template .= "create";
        return $this->render();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SliderRequest $request)
    {
        //
        $this->data["response"] = $this->slider_rep->create($request);
        if($this->data["response"])
            return redirect()->route("slider.edit",[$this->data["response"]->item_id])->with(["success"=>__("dashboard.dashboard_item_saved")]);
        
        return redirect()->back()->withErrors(["errors"=>"Error"]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $this->data["item"] = $this->slider_rep->find($id);
        // dd($this->data);
        $this->template .= "edit";
        return $this->render();
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $this->data["response"] = $this->slider_rep->update($request,$id);
        if($this->data["response"])
            return redirect()->back()->with(["success"=>__("dashboard.dashboard_item_updateded")]);
        
        return redirect()->back()->withErrors(["errors"=>"Error"]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        if($this->slider_rep->delete($id))
            return response()->json(["success"=>true]);
        return response()->json(["success"=>false],500);
    }
}

app/Http/Controllers/Dashboard/Specialization/SpecializationController.php
<?php

namespace App\Http\Controllers\Dashboard\Specialization;

use App\Http\Controllers\Dashboard\DashboardController as Controller;
use Illuminate\Http\Request;
use App\Repositories\SpecializationRepository;
use App\Http\Requests\SpecializationRequest;

class SpecializationController extends Controller
{
    public function __construct(SpecializationRepository $spec_rep){
        $this->spec_rep = $spec_rep;
        $this->template = "dashboard.page.specialization.";
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        
        if(request()->ajax()){
            $this->data = $this->spec_rep->getAllItems();
            return response()->json($this->data);
        }
        $this->template .= "index";
        return $this->render();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $this->template .= "create";
        return $this->render();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SpecializationRequest $request)
    {
        //
        $this->data["response"] = $this->spec_rep->create($request);
        if($this->data["response"])
            return redirect()->route("specialization.edit",[$this->data["response"]->item_id])->with(["success"=>__("dashboard.dashboard_item_saved")]);
        
        return redirect()->back()->withErrors(["errors"=>"Error"]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $this->data["item"] = $this->spec_rep->find($id);
        $this->template .= "edit";
        return $this->render();
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(SpecializationRequest $request, $id)
    {
        //
        $this->data["response"] = $this->spec_rep->update($request,$id);
        if($this->data["response"])
            return redirect()->back()->with(["success"=>__("dashboard.dashboard_item_updateded")]);
        
        return redirect()->back()->withErrors(["errors"=>"Error"]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        if($this->spec_rep->delete($id))
            return response()->json(["success"=>true]);
        return response()->json(["success"=>false],500);
    }
}

app/Http/Controllers/Dashboard/User/UserController.php
<?php

namespace App\Http\Controllers\Dashboard\User;

use Illuminate\Http\Request;
use App\Repositories\UserRepository;
use App\Repositories\RoleRepository;
use App\Http\Requests\UserRequest;
use App\Http\Controllers\Dashboard\DashboardController as Controller;

class UserController extends Controller
{
    public function __construct(RoleRepository $role_rep,UserRepository $user_rep){
        $this->user_rep = $user_rep;
        $this->role_rep = $role_rep;
        $this->template = "dashboard.page.user.";
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //

        if(request()->ajax()){
            $this->data = $this->user_rep->getAllItems();
            return response()->json($this->data);
        }
        $this->template .= "index";
        return $this->render();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $this->data["roles"] = $this->role_rep->all();
        $this->template .= "create";
        return $this->render();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequest $request)
    {
        //
        $this->data["response"] = $this->user_rep->create($request);
        if($this->data["response"])
            return redirect()->route("user.edit",[$this->data["response"]->id])->with(["success"=>__("dashboard.dashboard_item_saved")]);
        
        return redirect()->back()->withErrors(["errors"=>"Error"]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $this->data["roles"] = $this->role_rep->all();
        $this->data["item"] = $this->user_rep->find($id);
        $this->template .= "edit";
        return $this->render();
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $this->data["response"] = $this->user_rep->update($request,$id);
        if($this->data["response"])
            return redirect()->back()->with(["success"=>__("dashboard.dashboard_item_updateded")]);
        
        return redirect()->back()->withErrors(["errors"=>"Error"]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        if($this->user_rep->delete($id))
            return response()->json(["success"=>true]);
        return response()->json(["success"=>false],500);
    }
}

resources/views/dashboard/inc/footer.blade.php
<footer class="main-footer">
    <strong >Copyright &copy; {{Carbon\Carbon::now("Asia/Tbilisi")->format("Y")}}    </strong> All rights reserved.
</footer>

resources/views/dashboard/inc/header.blade.php
<header class="main-header">
    <a href="" class="logo"> <!-- Logo -->
        <span class="logo-mini">
                        <!--<b>A</b>BD-->
                        <img src="{{asset('assets/site/img/logo.png')}}" alt="">
                    </span>
        <span class="logo-lg">
                        <!--<b>Admin</b>BD-->
                        <img src="{{asset('assets/site/img/logo.png')}}" alt="">
                    </span>
    </a>
    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top">
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button"> <!-- Sidebar toggle button-->
            <span class="sr-only">Toggle navigation</span>
            <span class="pe-7s-keypad"></span>
        </a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">

                <li class="dropdown messages-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-language"></i>
                        <span class="label label-success">{{app()->getLocale()}}</span>
                    </a>
                    <ul class="dropdown-menu" style="height: 160px;">
                        <li class="header">{{__("menu.dashboard_language_label")}}</li>
                        <li>
                            <ul class="menu">

                                @foreach(LaravelLocalization::getSupportedLocales() as $localeCode => $properties)
                                    <li>
                                        <a rel="alternate" hreflang="{{ $localeCode }}" href="{{ LaravelLocalization::getLocalizedURL($localeCode, null, [], true) }}">
                                            {{ $properties['native'] }}
                                        </a>
                                    </li>
                                @endforeach


                            </ul>
                        </li>
                    </ul>


                <!-- settings -->
                <li class="dropdown dropdown-user">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <i class="pe-7s-settings"></i></a>
                    <ul class="dropdown-menu">
                        <li>
                            <form action="{{route('logout')}}" method="post" id="logaout">{{ csrf_field() }}</form>
                            <a href="javascript:void(0)" onclick="$('#logaout').submit()"><i class="pe-7s-key"></i> {{__("menu.dashboard_logout_label")}}</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

resources/views/dashboard/inc/menu.blade.php
<aside class="main-sidebar">
    <!-- sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel -->


        <!-- sidebar menu -->
        <ul class="sidebar-menu">
            <li class="header">{{__("menu.dashboard_main_nav_label")}}</li>
            <li>
                <a href="{{route("dashboard")}}"><i class="ti-home"></i> <span>{{__("menu.dashboard_index")}}</span>
                    <span class="pull-right-container">

                    </span>
                </a>
            </li>


            <li class="treeview">
                <a href="javascript:void(0)">
                    <i class="ti-layers"></i><span>{{__("menu.dashboard_slider")}}</span>
                    <span class="pull-right-container">
                        
                        <i class="fa fa-angle-left pull-right"></i>
                       
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{route('slider.create')}}">{{__("menu.dashboard_item_create")}}</a></li>
                    <li><a href="{{route('slider.index')}}">{{__("menu.dashboard_item_list")}}</a></li>

                </ul>
            </li>

            <li class="treeview">
                <a href="javascript:void(0)">
                    <i class="ti-microsoft"></i><span>{{__("menu.dashboard_proces")}}</span>
                    <span class="pull-right-container">
                        
                        <i class="fa fa-angle-left pull-right"></i>
                       
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{route('process.create')}}">{{__("menu.dashboard_item_create")}}</a></li>
                    <li><a href="{{route('process.index')}}">{{__("menu.dashboard_item_list")}}</a></li>

                </ul>
            </li>
            <li class="treeview">
                <a href="javascript:void(0)">
                    <i class="ti-ruler-pencil"></i><span>{{__("menu.dashboard_specialization")}}</span>
                    <span class="pull-right-container">
                        
                        <i class="fa fa-angle-left pull-right"></i>
                       
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{route('specialization.create')}}">{{__("menu.dashboard_item_create")}}</a></li>
                    <li><a href="{{route('specialization.index')}}">{{__("menu.dashboard_item_list")}}</a></li>

                </ul>
            </li>

            <li class="treeview">
                <a href="javascript:void(0)">
                    <i class="fa fa-users"></i><span>{{__("menu.dashboard_users")}}</span>
                    <span class="pull-right-container">
                        
                        <i class="fa fa-angle-left pull-right"></i>
                       
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{route('user.create')}}">{{__("menu.dashboard_item_create")}}</a></li>
                    <li><a href="{{route('user.index')}}">{{__("menu.dashboard_item_list")}}</a></li>

                </ul>
            </li>

            <li class="header">{{__("menu.dashboard_settings_label")}}</li>

            <li class="treeview">
                <a href="javascript:void(0)">
                    <i class="fa fa-google-wallet"></i><span>{{__("menu.dashboard_menu_meta")}}</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    
                    <li><a href="{{route('contact.edit',[1])}}">{{__("menu.dashboard_menu_og_meta")}}</a></li>
                    <li><a href="{{route('contact.edit',[4])}}">{{__("menu.dashboard_menu_meta")}}</a></li>
                </ul>
            </li>
          

            <li>
                <a href="{{url("elfinder")}}"><i class="ti-direction-alt"></i> <span>{{__("menu.dashboard_file_manager")}}</span>
                    <span class="pull-right-container">

                    </span>
                </a>
            </li>


           




        </ul>
    </div> <!-- /.sidebar -->
</aside>